apiVersion: v1
kind: PersistentVolume
metadata:
  name: employee-persistent-volume
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/employee-db
---
# Define a 'Persistent Volume Claim'(PVC) for Storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: employee-persistent-volume-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Configure 'Deployment' of postgres sql database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-database-deployment
  labels:
    app: employee
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee
      tier: db
  template:
    metadata:
      labels:
        app: employee
        tier: db
    spec:
      containers:
        - name: employee-database
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME
                  name: employee-db-config
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_HOST
                  name: employee-db-config
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: DB_USER
                  name: employee-db-config
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: employee-persistent-volume
      volumes:
        - name: employee-persistent-volume
          persistentVolumeClaim:
            claimName: employee-persistent-volume-claim
---

apiVersion: v1
kind: Service
metadata:
  name: employee-db-service
  labels:
    app: employee
    tier: db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: employee
    tier: db

