apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  POSTGRES_DB: ZW1wbG95ZWU=
  POSTGRES_USER: YWJoaXNoZWs=
  POSTGRES_PASSWORD: YWJoaTk4
  POSTGRES_HOST: ZW1wbG95ZWUtZGItc2VydmljZQ==
