apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: microservice-api
  template:
    metadata:
      labels:
        app: microservice-api
    spec:
      containers:
        - env:
            - name: POSTGRES_DB_URL
              valueFrom:
                configMapKeyRef:
                  key: DB_URL
                  name: api-config
            - name: POSTGRES_DB_USER
              valueFrom:
                secretKeyRef:
                  key: DB_USER
                  name: api-secrets
            - name: POSTGRES_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: api-secrets
          image: abhi9891/employee_api:latest
          name: microservice-api
          ports:
            - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: microservice-api
  type: LoadBalancer